name: CI - feature_maryam

on:
  push:
    branches: ["feature_maryam"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: pytest -q
